name = "vitex-net"
type = "webpack"
account_id = "55cb4036f82767a7f0f757a02a1ec8fd"
workers_dev = true

[site]
bucket = "./dist"
entry-point = "workers-site"

[env.production]
zone_id = "a00b24694c29f0fcfe676952da2ff47f"

[env.stage]
zone_id = "a00b24694c29f0fcfe676952da2ff47f"
